name: getting announcements

on: 
    repository_dispatch:
        types: [announcement_launched]
jobs:
  populateDB:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Get current date
          id: date
          run: |
                echo "::set-output name=date::$(date +'%Y%m%d')"
                
        - name: populate the DB
          env:
            PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
          run: |
            echo "$PAYLOAD_CONTEXT"
